# Generated by Django 3.0.4 on 2020-03-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='s_shoes',
        ),
        migrations.AddField(
            model_name='product',
            name='size_pants',
            field=models.ManyToManyField(to='shop.SizePants'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_shirt',
            field=models.ManyToManyField(to='shop.SizeShirt'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_shoes',
            field=models.ManyToManyField(to='shop.SizeShoes'),
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
