# Generated by Django 3.0.4 on 2020-03-16 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200316_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size_pants',
            field=models.ManyToManyField(blank=True, to='shop.SizePants'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size_shirt',
            field=models.ManyToManyField(blank=True, to='shop.SizeShirt'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size_shoes',
            field=models.ManyToManyField(blank=True, to='shop.SizeShoes'),
        ),
    ]
