# Generated by Django 3.0.4 on 2020-03-19 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200316_1312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('created',), 'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
    ]
