# Generated by Django 3.0.4 on 2020-04-29 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20200319_1500'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('created',)},
        ),
        migrations.AlterIndexTogether(
            name='product',
            index_together=set(),
        ),
    ]
